#!/usr/bin/env python

import commands, optparse, os, sys


if __name__ == '__main__':
    usage = """%prog bootstrap-file [header-file]

    Given a bootstrap file and an optional header file, create
    a new bootstrap file with a new header but the archive in
    the original file. Useful for testing new headers.

    The new bootstrap file has the same name as the old but
    with a -new suffix before the extension.
    """

    parser = optparse.OptionParser(usage=usage)

    options, args = parser.parse_args()

    if len(args) < 1:
        parser.error('You must supply a bootstrap file.')

    if len(args) > 2:
        parser.error('Bad arguments.')

    bootfile = args[0]
    header = args[1:] and args[1] or 'header.txt'

    cmd = "awk '/^__ARCHIVE_FOLLOWS__/ { print NR + 1; exit 0; }' %s" % bootfile

    status, skip = commands.getstatusoutput(cmd)
    if status != 0:
        print >>sys.stderr, 'Error in awk.'
        sys.exit(1)

    root, ext = os.path.splitext(bootfile)

    new_bootfile = root + '-new' + ext

    cmd = 'tail -n +%s %s | cat %s - > %s' % (skip, bootfile, header, new_bootfile)

    if os.system(cmd) != 0:
        print >>sys.stderr, 'Error making new header.'
        sys.exit(1)
